version: 1.0.0
grid:
  resolution: [4, 4, 4]
  bbox_min: [-0.2, -0.2, -0.2]
  bbox_max: [1.2, 1.2, 1.2]

parameters:
  epsilon_env: 5e-4
  epsilon_sil: 5e-4
  with_snapping: false
  with_insideness_check: true
